import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../shared/models/models.dart';
import '../../../shared/services/supabase_service.dart';

class _Message {
  final String text;
  final bool isUser;
  _Message(this.text, {required this.isUser});
}

class ChatbotScreen extends ConsumerStatefulWidget {
  const ChatbotScreen({super.key});

  @override
  ConsumerState<ChatbotScreen> createState() => _ChatbotScreenState();
}

class _ChatbotScreenState extends ConsumerState<ChatbotScreen> {
  final _messages  = <_Message>[];
  final _ctrl      = TextEditingController();
  final _scroll    = ScrollController();
  List<Report>? _reports;
  bool _typing     = false;

  static const _greet =
      'Hi! I am the FixMyRoad assistant. Ask me about your report status, '
      'repair estimates, or anything about the app.';

  @override
  void initState() {
    super.initState();
    _messages.add(_Message(_greet, isUser: false));
    _loadReports();
  }

  Future<void> _loadReports() async {
    _reports =
        await ref.read(supabaseServiceProvider).getMyReports();
  }

  void _send() async {
    final text = _ctrl.text.trim();
    if (text.isEmpty) return;
    _ctrl.clear();
    setState(() {
      _messages.add(_Message(text, isUser: true));
      _typing = true;
    });
    _scrollDown();

    await Future.delayed(const Duration(milliseconds: 600));
    final reply = _generateReply(text.toLowerCase());
    if (mounted) {
      setState(() {
        _messages.add(_Message(reply, isUser: false));
        _typing = false;
      });
      _scrollDown();
    }
  }

  String _generateReply(String input) {
    // Status queries
    if (input.contains('status') ||
        input.contains('my report') ||
        input.contains('where is')) {
      if (_reports == null || _reports!.isEmpty) {
        return "You haven't submitted any reports yet. Tap the + button on the map to report a pothole.";
      }
      final latest = _reports!.first;
      return 'Your latest report is currently: ${latest.statusLabel}.\n'
          '📍 ${latest.address ?? "Location recorded"}\n'
          '🕐 Submitted ${_timeAgo(latest.submittedAt)}\n'
          '${latest.aiResult != null ? "💰 Repair estimate: ${latest.aiResult!.costRangeLabel}" : ""}';
    }

    // When will it be fixed
    if (input.contains('when') && input.contains('fix')) {
      return 'Repair timelines depend on the government schedule and severity. '
          'Deep potholes are prioritised. You will receive a push notification '
          'when your report is assigned and when repair begins.';
    }

    // Cost
    if (input.contains('cost') || input.contains('price') ||
        input.contains('repair estimate')) {
      if (_reports?.firstOrNull?.aiResult?.repairCostMax != null) {
        final r = _reports!.first.aiResult!;
        return 'The estimated repair cost for your latest report is '
            '${r.costRangeLabel}. This is based on pothole depth and area '
            'calculated by our AI model.';
      }
      return 'Repair cost estimates are generated by our AI after you submit '
          'a photo. Check your report detail screen once analysis is complete.';
    }

    // Severity
    if (input.contains('severity') || input.contains('deep') ||
        input.contains('shallow') || input.contains('moderate')) {
      return 'Severity is determined by the depth of the pothole:\n'
          '🟢 Shallow — less than 2 cm (est.)\n'
          '🟡 Moderate — 2 to 5 cm (est.)\n'
          '🔴 Deep — more than 5 cm (est.)\n'
          'Deeper potholes get a higher priority score.';
    }

    // Upvote
    if (input.contains('upvote') || input.contains('vote')) {
      return 'You can upvote any existing pothole report to confirm you see '
          'the same issue. More upvotes raises the priority score, moving it '
          'higher in the engineer repair queue.';
    }

    // How many reports
    if (input.contains('how many') && input.contains('report')) {
      final count = _reports?.length ?? 0;
      return 'You have submitted $count report${count == 1 ? "" : "s"} so far. '
          'Thank you for helping improve your city!';
    }

    // Help / what can you do
    if (input.contains('help') || input.contains('what can you')) {
      return 'I can help you with:\n'
          '• Check your latest report status\n'
          '• Explain repair cost estimates\n'
          '• Tell you about severity levels\n'
          '• Explain how upvotes work\n'
          '• General questions about FixMyRoad\n\n'
          'Just type your question!';
    }

    // Hello
    if (input.contains('hello') || input.contains('hi') ||
        input.contains('hey')) {
      return 'Hello! How can I help you today? You can ask about your report '
          'status, repair costs, or how the app works.';
    }

    // Default
    return 'I am not sure about that. Try asking about your report status, '
        'repair estimates, or type "help" to see what I can do.';
  }

  void _scrollDown() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_scroll.hasClients) {
        _scroll.animateTo(
          _scroll.position.maxScrollExtent,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    });
  }

  String _timeAgo(DateTime dt) {
    final diff = DateTime.now().difference(dt);
    if (diff.inDays > 0)    return '${diff.inDays}d ago';
    if (diff.inHours > 0)   return '${diff.inHours}h ago';
    if (diff.inMinutes > 0) return '${diff.inMinutes}m ago';
    return 'just now';
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        title: Row(children: [
          CircleAvatar(
            radius: 16,
            backgroundColor: theme.colorScheme.primaryContainer,
            child: Icon(Icons.smart_toy_outlined,
                size: 18, color: theme.colorScheme.primary),
          ),
          const SizedBox(width: 10),
          const Text('FixMyRoad Assistant'),
        ]),
      ),
      body: Column(children: [
        Expanded(
          child: ListView.builder(
            controller: _scroll,
            padding: const EdgeInsets.all(16),
            itemCount: _messages.length + (_typing ? 1 : 0),
            itemBuilder: (_, i) {
              if (_typing && i == _messages.length) {
                return _TypingBubble();
              }
              final m = _messages[i];
              return _ChatBubble(message: m);
            },
          ),
        ),
        // Suggestion chips
        if (_messages.length == 1)
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            child: Row(children: [
              for (final s in [
                'My report status',
                'Repair cost',
                'How upvotes work',
                'Severity levels',
              ])
                Padding(
                  padding: const EdgeInsets.only(right: 8),
                  child: ActionChip(
                    label: Text(s, style: const TextStyle(fontSize: 12)),
                    onPressed: () {
                      _ctrl.text = s;
                      _send();
                    },
                  ),
                ),
            ]),
          ),
        // Input bar
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
          decoration: BoxDecoration(
            color: theme.colorScheme.surface,
            border: Border(
                top: BorderSide(
                    color: theme.colorScheme.outline.withOpacity(0.2))),
          ),
          child: SafeArea(
            child: Row(children: [
              Expanded(
                child: TextField(
                  controller: _ctrl,
                  decoration: const InputDecoration(
                    hintText: 'Ask a question...',
                    border: InputBorder.none,
                    contentPadding: EdgeInsets.symmetric(horizontal: 12),
                  ),
                  onSubmitted: (_) => _send(),
                  textInputAction: TextInputAction.send,
                ),
              ),
              IconButton(
                icon: const Icon(Icons.send_rounded),
                color: theme.colorScheme.primary,
                onPressed: _send,
              ),
            ]),
          ),
        ),
      ]),
    );
  }
}

class _ChatBubble extends StatelessWidget {
  final _Message message;
  const _ChatBubble({required this.message});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isUser = message.isUser;
    return Align(
      alignment: isUser ? Alignment.centerRight : Alignment.centerLeft,
      child: Container(
        margin: const EdgeInsets.only(bottom: 10),
        constraints: BoxConstraints(
            maxWidth: MediaQuery.of(context).size.width * 0.78),
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
        decoration: BoxDecoration(
          color: isUser
              ? theme.colorScheme.primary
              : theme.colorScheme.surfaceContainerHighest,
          borderRadius: BorderRadius.circular(16).copyWith(
            bottomRight: isUser ? const Radius.circular(4) : null,
            bottomLeft: !isUser ? const Radius.circular(4) : null,
          ),
        ),
        child: Text(
          message.text,
          style: TextStyle(
            color: isUser ? Colors.white : theme.colorScheme.onSurface,
            fontSize: 14,
            height: 1.4,
          ),
        ),
      ),
    );
  }
}

class _TypingBubble extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Align(
      alignment: Alignment.centerLeft,
      child: Container(
        margin: const EdgeInsets.only(bottom: 10),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        decoration: BoxDecoration(
          color: theme.colorScheme.surfaceContainerHighest,
          borderRadius: BorderRadius.circular(16)
              .copyWith(bottomLeft: const Radius.circular(4)),
        ),
        child: Row(mainAxisSize: MainAxisSize.min, children: [
          for (int i = 0; i < 3; i++) ...[
            if (i > 0) const SizedBox(width: 4),
            _Dot(delay: i * 200),
          ]
        ]),
      ),
    );
  }
}

class _Dot extends StatefulWidget {
  final int delay;
  const _Dot({required this.delay});

  @override
  State<_Dot> createState() => _DotState();
}

class _DotState extends State<_Dot> with SingleTickerProviderStateMixin {
  late AnimationController _ctrl;
  late Animation<double> _anim;

  @override
  void initState() {
    super.initState();
    _ctrl = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 600))
      ..repeat(reverse: true);
    _anim = Tween<double>(begin: 0.3, end: 1.0).animate(
        CurvedAnimation(parent: _ctrl, curve: Curves.easeInOut));
    Future.delayed(Duration(milliseconds: widget.delay), () {
      if (mounted) _ctrl.forward();
    });
  }

  @override
  void dispose() { _ctrl.dispose(); super.dispose(); }

  @override
  Widget build(BuildContext context) => FadeTransition(
        opacity: _anim,
        child: Container(
          width: 7,
          height: 7,
          decoration: BoxDecoration(
            color: Theme.of(context).colorScheme.onSurfaceVariant,
            shape: BoxShape.circle,
          ),
        ),
      );
}
